apiVersion: apps/v1
kind: Deployment
metadata:
 name: javadeployment-prod
spec:
 strategy:
   type: RollingUpdate
 replicas: 2
 selector:
   matchLabels:
     app: frontend02
 template:
   metadata:
    name: javaPod
    labels:
      app: frontend02
   spec:
    containers:
    - name: myjava
      imagePullPolicy: Always
      image: durgaprasadtibco/tomcat-webapp:v1
      ports:
      - containerPort: 8080
